#! /bin/bash


# Details to deploy client to github pages
source .env
BASE_HREF="$GITHUB_REPO_NAME"

echo -e """ \033[32m
===========================
DEPLOYING BUNDLES TO GITHUB
BASE_HREF : \033[36m${BASE_HREF} \033[32m
=========================== \033[0m
"""

# Build pages for github deployment
PUBLIC_URL="/$BASE_HREF/" REACT_APP_BASE_HREF="/$BASE_HREF/" npm run build
rsync -a build/ "build-$BASE_HREF/"

# Copy index.html to 404.html to enable url-direct navigation
cp "build-$BASE_HREF/index.html" "build-$BASE_HREF/404.html"

# Build some node code with env vars injected
read -r -d '' NODECMD << EOM
  const ghpages = require("gh-pages");
  ghpages.publish("build-${GITHUB_REPO_NAME}", function (err) {
    if (!!err) {
      console.log("OH NO! STH WENT WRONG :(", err);
      process.exit(1);
    }
    console.log("DEPLOYED TO: https://${GITHUB_USER_NAME}.github.io/${GITHUB_REPO_NAME}/");
  })
EOM

# Execute node code
node -e "$NODECMD"
